### ISSUE TITLE
run it on Linux

### ISSUE THREAD

**Issue by AlbionS** [sueda/fbx-extract#1]
Hi, I would really like to try this out.

could you please give us more info how to make it run ?

I would like to run it on a Linux environment if that's possible.

Best,
Albion

**Comment by sueda** [comment]
I added the instructions for building and running to the readme file. Please note that this project has only been tested on the example fbx file in the data folder.

**Comment by AlbionS** [comment]
Thanks a lot.

I am not able to add the variable of GLM_INCLUDE_DIR, not my strongest point to install programs !

CMake Error at CMakeLists.txt:31 (MESSAGE):
  Please point the environment variable GLM_INCLUDE_DIR to the root directory
  of your GLM installation.

**Comment by sueda** [comment]
There is a writeup [here](https://people.engr.tamu.edu/sueda/courses/CSCE489/2020F/labs/L00/index.html) on setting up the environment.
