### ISSUE TITLE
how to use skeletal animation

### ISSUE THREAD

**Issue by luyangzhu** [sueda/fbx-extract#2]
Hi, I tried to visualize the extracted skeletal animation. For the rest pose (1st frame), directly visualizing the bone positions (x,y,z) gives me a rest pose skeleton. For the animation frames, visualizing the bone positions does not give any meaningful skeleton. I am curious how can I get the correct skeleton sequence from the extracted skeletal animation. 

I tried to guess the meaning of per frame rotation and translation (e.g. joint coordinate to world coordinate transform, world coordinate to joint coordinate transform, product of transformation matrix and bind matrix etc) and compute the per frame skeleton accordingly, but none of it correct. Maybe I am missing something.

BTW, my fbx file is downloaded from mixamo.

**Comment by sueda** [comment]
> Each subsequent line is a frame with "boneCount" sets of quaternions (x,y,z,w) and positions (x,y,z).

The quaternion and the position forms the transformation matrix of the bone wrt the world and not wrt to its parent. This library does not keep track of the hierarchy of the joints.

**Comment by luyangzhu** [comment]
Thanks for your reply. In that case, directly visualizing the position should provide correct skeleton. Maybe I can try another fbx file.

**Comment by sueda** [comment]
It may be that it only works with some of the fbx files. It has only been tested with the file in this [assignment](https://people.engr.tamu.edu/sueda/courses/CSCE489/2020F/assignments/A2/index.html). I hope to get to the bottom of this issue eventually.

**Comment by luyangzhu** [comment]
Sounds good. Thanks for the work!
