### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by marosiy** [sueda/fbx-extract#3]
Hello, thank you for creating wonderful program. 

I have a question.
I tried this program but segmentation fault error occurred.

My fbx file is simple.
My fbx file has 3d object data, skin and animation.

If you know this error, Please give me something suggests.

=== geometry ===
pSphere1: 2280 verts, 439 unique <br>
pSphere2: 2280 verts, 439 unique
Saving to bone_pSphere1.obj
Saving to bone_pSphere2.obj
=== skin ===
pSphere1: 2280 vertices
pSphere2: 2280 vertices
Saving to bone_pSphere1_skin.txt
Saving to bone_pSphere2_skin.txt
=== skeleton ===
2 clusters
zsh: segmentation fault  ./fbx-extract 

<img width="482" alt="Screen Shot 2022-01-09 at 0 55 52" src="https://user-images.githubusercontent.com/46900773/148650986-cde6b543-2a7e-4325-9c8b-711dcae0dd72.png">

**Comment by ZiyanXiong** [comment]
I have updated the code. Now it extracts the skeleton data in a different way from previous version. Could you please try the new verison code and see if it sovles your problem? 

This program assumes that the input FBX file are downloaded from [Mixamo](https://www.mixamo.com).  It might not work for fbx files which store the skeleton data in other structures.

**Comment by marosiy** [comment]
I tried my fbx file and I could extract information successfully.
My fbx is created by Maya.
Thank you for modification !
